name: Check Project Metadata

on:
  push:
    branches: [main]
    paths:
      - "src/scribe_data/resources/**/*.json"
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
    paths:
      - "src/scribe_data/resources/**/*.json"

jobs:
  structure-check:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.11"

    runs-on: ${{ matrix.os }}

    name: Run Check Project Metadata

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add project root to PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run check_project_metadata.py
        working-directory: ./src/scribe_data/check
        run: python check_project_metadata.py

      - name: Post-run status
        if: failure()
        run: echo "Project metadata check failed. Please fix the reported errors."
